os:
  - linux
sudo: false
branches:
  # Build all branches
  only:
    - /.*/
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
before_script:
  - git clone --branch stable --depth 1 https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script:
  - flutter packages get
  - flutter analyze --no-pub --no-current-package ./lib ./test ./example
  - flutter format -n --set-exit-if-changed ./lib ./test ./example || travis_terminate 1
  - flutter test --coverage --coverage-path=lcov.info
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Avoid re-downloading packages across different builds if possible.
cache:
  directories:
    - $HOME/.pub-cache
