name: extensive_date_range_picker
description: Flutter widget that provides an extensive date and time range picker.
version: 1.2.0
homepage: https://github.com/larryaasen/extensive_date_range_picker

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  # From dart.dev: internationalization and localization facilities
  intl: ^0.18.0

  # From jama5262 - parsing, manipulating, querying and formatting dates
  jiffy: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
